FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY angular.json tsconfig.json ./
COPY src ./src

EXPOSE 4200
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "1000"]
